Fix `IllegalReferenceCountException` in `ResponseDecoder`
Releasing the `ByteBuf` given as an argument to a `MessageToMessageDecoder`
implementation causes this error later:
```
reactivemongo.io.netty.handler.codec.DecoderException: reactivemongo.io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
 	at reactivemongo.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	at reactivemongo.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
 Caused by: reactivemongo.io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
 	at reactivemongo.io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:124)
 	at reactivemongo.io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107)
 	at reactivemongo.io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
 	at reactivemongo.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```
since the decoder will [release the ByteBuf
itself](https://netty.io/4.1/api/io/netty/handler/codec/MessageToMessageDecoder.html)

> Be aware that you need to call ReferenceCounted.retain() on messages that are
> just passed through if they are of type ReferenceCounted. This is needed as
> the MessageToMessageDecoder will call ReferenceCounted.release() on decoded
>  messages.